[package]
name = "traincrew-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.58.0", features = ["Win32", "Win32_System", "Win32_System_Memory", "Win32_Security", "Win32_System_SystemServices"] }
